# 文件名建议统一为 preview-publish
# 应用 preview.yml 的 demo

# name: PREVIEW_PUBLISH

# on:
#   workflow_run:
#     workflows: ["MAIN_PULL_REQUEST"]
#     types:
#       - completed

# jobs:
#   call-preview:
#     uses: kongying-tavern/docs/.github/workflows/preview.yml@next
#     secrets:
#       SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
